### ISSUE TITLE
Import data from Japanese datamine

### ISSUE THREAD

**Issue by Psyramics** [jnbooth/chaldeas#1]
I was working on something similar, then went on vacation and completely lost the thread. The goal was to allow a Master to compare Servants that they actually own at levels they've actually reached, against targets of their choosing. 

Part of that is an importer script that takes the raw data mine from Kazemai, translates it into more usable formats, and extracts strings that need translation. It's [here](https://github.com/Psyramics/chaldea-damage-room/blob/master/Gruntfile.js) if you're interested. I use Grunt here, but the actual importer only requires nodejs.

The final setup would have a cheapo AWS server listening to the Kazemai repo for updates, running the translation script, and committing back to my repo to be published to Github Pages.

**Comment by andymcwraith** [comment]
I like this idea.

Would prevent having to manually add (and possibly edit) servant data in the database, which I assume is being done here

**Comment by jnbooth** [comment]
I will definitely use this, for error-checking at the least. Any idea what's going on with the "expCurve" field?  CHALDEAS is currently lacking any information about growth curves.

**Comment by Psyramics** [comment]
I know all about it.

Every Servant references an expCurve, of which there are several. Each expCurve is basically just a map of level => modifier. [This](https://github.com/Psyramics/chaldea-damage-room/blob/master/data/curves.json) is the simplest structure for any given expCurve. The keys of the array are the level, and value is the modifier. 

To determine the stat of a given Servant at a given level, you follow these steps:
1. Get the Servant's base and max values for the stat
2. You get the modifier for the Servant's expCurve at the Servant's level
3. You plug them into this formula: ```stat = floor(base + ((max - base) * modifier / 1000))```
4. Add Fous. 

Don't have to worry about grails or anything, the expCurve has the full range from 0 to 100.

The most annoying part was figuring that out, because the raw data looks like it was dumped from a sql database and kazemai does 0 processing on it to make it more readable.

**Comment by jnbooth** [comment]
Absolutely fantastic work. I will get right to work integrating this.

**Comment by jnbooth** [comment]
Growth curves are now implemented as part of the My Servants feature. Also added error-checking, but for now it matches info against GrandOrder.Wiki because they've got everything translated properly.
