### ISSUE TITLE
Filters of the same 'filter' type should work

### ISSUE THREAD

**Issue by andymcwraith** [jnbooth/chaldeas#2]
Feel free to close this issue if this was intended behaviour.
If I select multiple filters of the same type they cancel each other out.

In this example I wanted to filter by 'Arts' and 'Buster' NP types:
![chaldeas_filter_error_1](https://user-images.githubusercontent.com/16784411/44686235-a9cc5f80-aaa1-11e8-8429-a0e2b880bb74.PNG)

**Comment by jnbooth** [comment]
I've moved mutually exclusive categories to the left and turned them into checkboxes to avoid this problem.
